# Generated by Django 2.1.3 on 2018-11-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
    ]
