# Generated by Django 2.1.3 on 2018-11-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='extras',
            field=models.TextField(null=True),
        ),
    ]
