# Generated by Django 2.1.3 on 2018-11-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Samochód', 'verbose_name_plural': 'Samochody'},
        ),
        migrations.AddField(
            model_name='car',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Przebieg'),
        ),
    ]
