# Generated by Django 2.1.3 on 2018-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_auto_20181120_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True, verbose_name='Przebieg'),
        ),
    ]
