# Generated by Django 2.1.3 on 2018-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0003_auto_20181120_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('user_name', models.CharField(max_length=20, verbose_name='imię')),
                ('user_surname', models.CharField(max_length=50, verbose_name='nazwisko')),
                ('user_email', models.CharField(max_length=60, verbose_name='email')),
                ('user_phone', models.IntegerField(max_length=15, verbose_name='telefon')),
                ('user_dateofbirth', models.IntegerField(max_length=15, verbose_name='data urodzenia')),
            ],
        ),
    ]
