# Generated by Django 2.1.3 on 2018-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('desc', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miasto',
                'verbose_name_plural': 'Miasta',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=1)),
                ('desc', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Województwo',
                'verbose_name_plural': 'Województwa',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='dist',
            field=models.ForeignKey(on_delete='PROTECT', to='Rental.District'),
        ),
    ]
