# Generated by Django 2.1.3 on 2018-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0005_auto_20181122_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Rodzaj')),
                ('population', models.IntegerField(verbose_name='Ilość mieszkańców')),
                ('desc', models.TextField(verbose_name='Opis')),
                ('add_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Typ miasta',
                'verbose_name_plural': 'Typy miast',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.ForeignKey(on_delete='PROTECT', to='Rental.CityType'),
        ),
    ]
